spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/chodan_dev_v2?serverTimezone=Asia/Seoul&sendFractionalSeconds=false #host.docker.internal
    username: admin
    password: 4S9B7vO5AHCK3UfMr8h8
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
    properties:
      default_batch_fetch_size: 1000 #최적화 옵션
      hibernate.jdbc:
        time_zone: Asia/Seoul
        batch_size: 1000
        order_inserts: true
        order_updates: true
        auto_quote_keyword: true # 예약어 사용가능
        globally_quoted_identifiers: true # 예약어 사용가능
        show_sql: true # sql 로깅
        generate_statistics: true # 쿼리수행 통계
        format_sql: true # SQL문 정렬하여 출력
        highlight_sql: true # SQL문 색 부여
    open-in-view: false
  jwt:
    header: Authorization
    secretKey: bIVQBDIis9GqVow_0Wuls-Ukm8yY6LHqeybPYoVxdwo
  url:
    base: http://localhost:8805

# Config 설정
decorator:
  datasource:
    p6spy:
      enable-logging: true

springdoc:
  swagger-ui:
    url:
    doc-expansion: none
    tags-sorter: alpha
    operations-sorter: method
  override-with-generic-response: false # swagger 기본 응답 false

logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    root: info
    com.restApi.restApiSpringBootApp: debug
    org.springframework: WARN
    hama.chodan.chodanjavaapi.global.config.aop: debug # AOP 로그 설정
    hama.chodan.chodanjavaapi.global.advice.exception: debug # ExceptionAdvice 로그 설정
    hibernate:
      orm:
        jdbc:
          bind: TRACE # jdbc bind value 로깅 처리
  file:
    name: /var/www/log/tteokbokki-api.log